---
- hosts: ubuntu
  tasks:
  - name: Install/upgrade stock python modules
    become: yes
    apt:
      pkg:
        - python-minimal
        - python3-venv
        - python-apt
      update_cache: yes
      cache_valid_time: 3600
      state: latest
      autoremove: yes

  - name: Install/upgrade awscli & python module
    become: yes
    apt:
      pkg:
        - awscli
        - python3-boto3
      update_cache: yes
      cache_valid_time: 3600
      state: latest
      autoremove: yes

  # requires network variable to be set
  - name: Install or upgrade cifs-utils
    become: yes
    apt:
      update_cache: yes
      cache_valid_time: 3600
      name: cifs-utils
      state: latest
      autoremove: yes
    when:
      - network != 'DMZ' # skip this package on DMZ hosts

  - name: Remove snapd
    become: yes
    apt:
      update_cache: yes
      cache_valid_time: 3600
      name: snapd
      state: absent
      autoremove: yes
