--- # Version 1.1.0
- hosts: localhost
  vars_files:
  - vars/vmware_vars.yml
  vars_prompt:
   - name: vm_name
     prompt: Enter the name of the VM
     private: no
   - name: vm_network
     prompt: Enter the name of the network for the VM
     default: "{{network_default}}"
     private: no
   - name: vm_datastore
     prompt: Enter the name of the datastore to put the VM on
     default: "{{datastore_default}}"
     private: no
   - name: vm_boot
     prompt: Boot VM after creation?
     default: 'Yes'
     private: no
  tasks:
   - name: Create VM
     delegate_to: localhost
     vmware_guest:
       username: "{{esx_username}}"
       password: "{{esx_password}}"
       validate_certs: yes
       hostname: "{{esx_hostname}}"
       folder: /ha-datacenter/vm/
       name: "{{vm_name}}"
       state: present
       guest_id: ubuntu64Guest
       hardware:
         version: 14
         boot_firmware: efi
         hotadd_cpu: true
         hotadd_memory: true
         memory_mb: 1024
         num_cpus: 1
         scsi: paravirtual
       disk:
       - size_gb: 12
         type: thin
         disk_mode: persistent
         datastore: "{{vm_datastore}}"
       cdrom:
       - controller_type: ide
         controller_number: 0
         unit_number: 0
         type: iso
         iso_path: '[ISO] ubuntu-20.04-live-server-amd64.iso'
       networks:
       - name: "{{vm_network}}"
         device_type: vmxnet3
       customvalues:
       - key: sched.swap.dir
         value: '/vmfs/volumes/local-ssd/swap'
       wait_for_ip_address: no
     register: deploy_vm

   - name: Configure VM boot settings
     delegate_to: localhost
     vmware_guest_boot_manager:
       hostname: "{{esx_hostname}}"
       username: "{{esx_username}}"
       password: "{{esx_password}}"
       validate_certs: yes
       name: "{{vm_name}}"
       boot_delay: 3000
       secure_boot_enabled: True

   - name: Boot VM
     delegate_to: localhost
     vmware_guest_powerstate:
       hostname: "{{esx_hostname}}"
       username: "{{esx_username}}"
       password: "{{esx_password}}"
       validate_certs: yes
       name: "{{ vm_name }}"
       state: powered-on
     when: vm_boot|bool
