---

- name: Set timezone to America/Los_Angeles
  become: yes
  timezone:
    name: America/Los_Angeles
  notify: restart cron

- name: Install/upgrade standard packages
  become: yes
  apt:
    pkg:
      - awscli
      - net-tools
      - python3-minimal
      - python3-venv
      - python3-apt
      - python3-boto3
      - unattended-upgrades
      - ssl-cert
    update_cache: yes
    cache_valid_time: 3600
    state: latest
    autoremove: yes

# requires network variable to be set
- name: Install or upgrade cifs-utils
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name: cifs-utils
    state: latest
    autoremove: yes
  when:
    - network != 'DMZ' # skip this package on DMZ hosts

- name: Remove snapd
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name: snapd
    state: absent
    autoremove: yes

- name: configure syslog forwarding
  become: yes
  template:
    src: 10-forward.conf
    dest: /etc/rsyslog.d/10-forward.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    backup: yes
  notify: restart rsyslog

- name: Configure timesyncd fallback
  become: yes
  lineinfile:
    path: /etc/systemd/timesyncd.conf
    state: present
    regexp: 'FallbackNTP='
    line: "FallbackNTP=ntp"

- name: Install & configure ssmtp # skip if smtp_server is defined for a host or server is in DMZ
  block:
  - name: Install/upgrade ssmtp
    become: yes
    apt:
      update_cache: yes
      cache_valid_time: 3600
      name: ssmtp
      state: latest
      autoremove: yes

  - name: configure ssmtp
    become: yes
    template:
      src: ssmtp.j2
      dest: /etc/ssmtp/ssmtp.conf
      owner: root
      group: mail
      mode: u=rw,g=r,o=
      backup: yes
  when: smtp_server is not defined and network != 'DMZ'
  tags: smtp

- name: Set auto-download for package updates
  become: yes
  lineinfile:
    path: /etc/apt/apt.conf.d/10periodic
    state: present
    regexp: 'APT::Periodic::Download-Upgradeable-Packages'
    line: 'APT::Periodic::Download-Upgradeable-Packages "1";'
  tags: unattended

- name: Set autoclean for apt packages
  become: yes
  lineinfile:
    path: /etc/apt/apt.conf.d/10periodic
    state: present
    regexp: 'APT::Periodic::AutocleanInterval'
    line: 'APT::Periodic::AutocleanInterval "7";'
  tags: unattended

- name: Set mail notification for unattended-upgrade package
  become: yes
  lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    state: present
    regexp: 'Unattended-Upgrade::Mail '
    line: 'Unattended-Upgrade::Mail "root";'
  tags: unattended

- name: Set autoremove unused kernel packages
  become: yes
  lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    state: present
    regexp: 'Unattended-Upgrade::Remove-Unused-Kernel-Packages'
    line: 'Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";'
  tags: unattended

- name: Set autoremove new unused dependencies
  become: yes
  lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    state: present
    regexp: 'Unattended-Upgrade::Remove-New-Unused-Dependencies'
    line: 'Unattended-Upgrade::Remove-New-Unused-Dependencies "true";'
  tags: unattended

- name: Set autoremove of unused packages
  become: yes
  lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    state: present
    regexp: 'Unattended-Upgrade::Remove-Unused-Dependencies'
    line: 'Unattended-Upgrade::Remove-Unused-Dependencies "true";'
  tags: unattended

- name: Enable unattended-upgrades loggin to syslog
  become: yes
  lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    state: present
    regexp: 'Unattended-Upgrade::SyslogEnable'
    line: 'Unattended-Upgrade::SyslogEnable "true";'
  tags: unattended

- name: Create directory for apt-daily.timer override
  become: yes
  file:
    path: /etc/systemd/system/apt-daily.timer.d
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  tags: unattended

- name: Set apt-update time to 2300-2315
  become: yes
  copy:
    content: |
      [Timer]
      OnCalendar=
      OnCalendar=01:00
      RandomizedDelaySec=15m
    dest: /etc/systemd/system/apt-daily.timer.d/override.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags: unattended

- name: Create directory for apt-daily-upgrade.timer override
  become: yes
  file:
    path: /etc/systemd/system/apt-daily-upgrade.timer.d
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  tags: unattended

- name: Set unattended-upgrade time to 0300-0310
  become: yes
  copy:
    content: |
      [Timer]
      OnCalendar=
      OnCalendar=03:00
      RandomizedDelaySec=10m
    dest: /etc/systemd/system/apt-daily-upgrade.timer.d/override.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags: unattended

# nas user/group used for consistency even when not mounting remote filesystems
- name: Create 'nas' group
  become: yes
  group:
    name: nas
    state: present
    gid: 900
    system: yes

- name: Create 'nas' user
  become: yes
  user:
    name: nas
    state: present
    system: yes
    uid: 900
    group: nas
    home: /nonexistent
    shell: /usr/sbin/nologin
    create_home: no

- name: Checking for central nas directory in /mnt
  become: yes
  stat:
    path: /mnt/nas
  register: nas

# restricting permissions on mount target to prevent accidental writing when a mount error occurs.
- name: Create /mnt/nas directory
  become: yes
  file:
    path: /mnt/nas
    state: directory
    owner: nas
    group: nas
    mode: u=rx,g=rx,o=rx
  when: not nas.stat.isdir is defined

#mount centralized remote filesystems for non DMZ/LAB servers
- include_tasks: cifs-mount.yml
  when:
    - network != 'DMZ' and network != 'LAB' # skip cifs configuration on DMZ and LAB hosts
