---
- name: Add Docker GPG apt Key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Official Docker Repository
  become: yes
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
    filename: docker
    state: present

- name: Install docker-compose
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name: docker-compose
    state: latest
    autoremove: yes
