---
# Ubuntu specific

- name: Docker GPG apt key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Official Docker repo
  become: yes
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
    filename: docker
    state: present

- name: docker-compose package
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name: docker-compose
    state: latest
    autoremove: yes

- name: /opt/docker-compose directory
  become: yes
  file:
    path: /opt/docker-compose
    state: directory
    owner: root
    group: docker
    mode: u=rwx,g=rx,o=

- name: Check for telegraf
  become: yes
  stat:
    path: /etc/telegraf/telegraf.d
  register: telegraf

- name: telegraf user in docker group
  become: yes
  user:
    name: telegraf
    groups: docker
    append: yes
  notify: Restart telegraf
  when: telegraf.stat.isdir is defined

- name: Configure telegraf docker plugin
  become: yes
  copy:
    src: inputs.docker.conf
    dest: "/etc/telegraf/telegraf.d/inputs.docker.conf"
    owner: telegraf
    group: telegraf
    mode: u=rw,g=r,o=
  notify: Restart telegraf
  when: telegraf.stat.isdir is defined
