---
- name: Telegraf Ubuntu tasks
  include_tasks:
    ubuntu.yml
  when:
    - ansible_distribution == 'Ubuntu'
    - (network != 'DMZ') and (network != 'LAB')

- name: Telegraf Raspberry Pi tasks
  include_tasks:
    raspberry.yml
  when:
    - (ansible_lsb.id is defined) and (ansible_lsb.id == 'Raspbian')
    - ansible_distribution == 'Debian'

- name: Telgraf FreeNAS tasks
  include_tasks:
    freenas.yml
  when:
    - ansible_distribution == 'FreeBSD'
