---
  #Default
- set_fact:
    telegraf_os: "Ubuntu"
    telegraf_etc_dir: "/etc/telegraf"

- name: Install Influxdata Repo Prerequisites
  become: yes
  apt:
    pkg:
      - apt-transport-https
    update_cache: yes
    cache_valid_time: 3600
    state: latest
    autoremove: yes

- name: Add Influxdata apt key
  become: yes
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present

- name: Add Influxdata Repo
  become: yes
  apt_repository:
    repo: deb https://repos.influxdata.com/{{ansible_distribution|lower}} {{ansible_distribution_release|lower}} stable
    filename: influxdata
    state: present

- name: telegraf package
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name: telegraf
    state: latest
    policy_rc_d: 101
    autoremove: yes

- name: Configure telegraf
  become: yes
  template:
    src: telegraf.j2
    dest: "{{telegraf_etc_dir}}/telegraf.conf"
    owner: telegraf
    group: telegraf
    mode: u=rw,g=r,o=
    backup: yes
  notify: Restart telegraf

#requires influxdb_server variable
- name: Configure telegraf output to influxdb
  become: yes
  template:
    src: outputs.influxdb.j2
    dest: "{{telegraf_etc_dir}}/telegraf.d/outputs.influxdb.conf"
    owner: telegraf
    group: telegraf
    mode: u=rw,g=r,o=
    backup: yes
  notify: Restart telegraf

- name: Configure telegraf x509 input plugin
  become: yes
  template:
    src: inputs.x509_cert.j2
    dest: "{{telegraf_etc_dir}}/telegraf.d/inputs.x509_cert.conf"
    owner: telegraf
    group: telegraf
    mode: u=rw,g=r,o=
    backup: yes
  notify: Restart telegraf

- name: Configure telegraf default input plugins
  become: yes
  copy:
    src: inputs.default.conf
    dest: "{{telegraf_etc_dir}}/telegraf.d/inputs.default.conf"
    owner: telegraf
    group: telegraf
    mode: u=rw,g=r,o=
    backup: yes
  notify: Restart telegraf

# needed to pull gpu temps on Pi
- name: telegraf group membership
  become: yes
  user:
    name: telegraf
    groups: video
    append: yes
  notify: Restart telegraf
  when: ansible_architecture == 'aarch64'

- name: telegraf Pi plugin
  become: yes
  copy:
    src: inputs.pi.conf
    dest: "{{telegraf_etc_dir}}/telegraf.d/inputs.pi.conf"
    owner: telegraf
    group: telegraf
    mode: u=rw,g=r,o=
    backup: yes
  notify: Restart telegraf
  when: ansible_architecture == 'aarch64'

- name: telegraf systemd_units plugin
  become: yes
  copy:
    src: inputs.systemd_units.conf
    dest: "{{telegraf_etc_dir}}/telegraf.d/inputs.systemd_units.conf"
    owner: telegraf
    group: telegraf
    mode: u=rw,g=r,o=
    backup: yes
  notify: Restart telegraf

- name: influxdb Intermediate CA
  become: yes
  get_url:
    url: https://letsencrypt.org/certs/lets-encrypt-r3-cross-signed.pem
    dest: "{{telegraf_etc_dir}}/ca.pem"
    owner: telegraf
    group: telegraf
    mode: u=rw,g=r,o=

# TODO Add telegraf systemctl override file for collecter server
